### ISSUE TITLE
Behave seems to Ignore `pyproject.toml` (in working directory)

### ISSUE THREAD

**Issue by paulschroeder-tomtom** [behave/behave#1171]
`behave` seems to ignore my `pyproject.toml`. In the example below its ignoring the `tags` but it also dosnt honor any other configs given via `pyproject.toml` :cry: 
```toml
[tool.poetry]
name = "int-tests"
# ...
[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.31.0"
behave = {git = "https://github.com/behave/behave.git", rev = "v1.2.7.dev5"}
behave-html-formatter = "^0.9.10"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.behave]
tags = [
    "-@ci",
    "-@local",
    "-@skip", # Skip tests that are not ready to run
]
paths = [
    "features",
]
```

```bash
$ behave features/info.feature
USING RUNNER: behave.runner:Runner
Feature: Info endpoint # features/info.feature:1
  Test the info endpoint of the oAPI.
  @ci
  Scenario: Get info (the regular case, talking deployed APIs as service principals)  # features/info.feature:5
    When an user wants to call GET /info                                              # steps/when.py:10 0.410s
    Then the response status code is 200                                              # steps/then.py:15 0.000s
    And we expect the following user to be returned: Application                      # steps/then.py:34 0.000s
      Assertion Failed: 
      Expected: 'Application'
           but: was 'Paul Schroeder'
      
      Captured logging:
      WARNING:root:payload not YAML parsable:
      None

    And we expect the following roles to be returned: customer                        # None

  @local
  Scenario: Get info (if we are developing against locally ran APIs)  # features/info.feature:12
    When an user wants to call GET /info                              # steps/when.py:10 0.058s
    Then the response status code is 200                              # steps/then.py:15 0.000s
    And we expect the following user to be returned: Dev user         # steps/then.py:34 0.000s
      Assertion Failed: 
      Expected: 'Dev user'
           but: was 'Paul Schroeder'
      
      Captured logging:
      WARNING:root:payload not YAML parsable:
      None

    And we expect no roles                                            # None

  @system
  Scenario: Get info (talk to a remote API as the current system/azure AD user)         # features/info.feature:19
    When an user wants to call GET /info                                                # steps/when.py:10 0.041s
    Then the response status code is 200                                                # steps/then.py:15 0.000s
    And we expect the following roles to be returned: customer                          # steps/then.py:22 0.000s
    And we expect the following user to be returned: <system_logged_in_users_full_name> # steps/then.py:34 0.000s


Failing scenarios:
  features/info.feature:5  Get info (the regular case, talking deployed APIs as service principals)
  features/info.feature:12  Get info (if we are developing against locally ran APIs)

0 features passed, 1 failed, 0 skipped
1 scenario passed, 2 failed, 0 skipped
8 steps passed, 2 failed, 2 skipped, 0 undefined
Took 0m0.509s
```

```bash
$ behave --version
behave 1.2.7.dev5
```

Folder structure (stripped)
```bash
$ tree
.
├── environment.py
├── features
│   └── info.feature
├── __init__.py
├── poetry.lock
├── pyproject.toml
├── steps
│   ├── __init__.py
│   ├── given.py
│   ├── then.py
│   └── when.py
└── utils.py
```
