### ISSUE TITLE
How to use behave in different environments?

### ISSUE THREAD

**Issue by jlming6** [behave/behave#298]
Hi guys, 
This is not an issue, just a question.

This is a usual case i think, we have one service for several environments, prod, stage, dev, etc.
They have exactly same logic but some different settings (variables).
Is there any best practices or suggestions for this?
Or is there any examples for this?

Thanks so much.

**Comment by s1ider** [comment]
Hi,

You're right, it's a common case. 
I prefer to specify required settings in somethings like _environments.yml_:

```yaml
stage:
    base_url: http://stage_url.com
    key_1: value_1
    key_2: value_2
prod:
    base_url: http://prod_url.com
    key_1: value_1
    key_2: value_2
...
```

Then you can easily specify current environment with ENV variable and read it in _environments.py_:

```python
import os
import yaml

def before_all(context):
    environs = yaml.load(open('environments.yml').read())
    env = os.getenv('ENV', 'stage')
    context.base_url = environs[env]['base_url']
    ...
```

Docs might help a little http://behave.readthedocs.org/en/latest/tutorial.html#environmental-controls.
